### ISSUE TITLE
you couldn't translate Chinese into id property?

### ISSUE THREAD

**Issue by JimmyVV** [valeriangalliat/markdown-it-anchor#17] opened 2016-05-23 12:19 UTC
what a shame~ author, why not you translate Chinese?

**Comment by valeriangalliat** [comment] 2016-05-23 13:19
Duplicate of #10; the problem is the ID property is determined with strings.js, which seems to support only western languages.

What slugification module would you advise instead? I might switch from strings.js to something that have better language support it in a next major release (will be a breaking change).

Meanwhile, you can configure your own `slugify` function (takes the title text as argument, returns the ID), to make it support Chinese.

**Comment by JimmyVV** [comment] 2016-05-23 14:57
en. maybe you misunderstand my mean. I just want you just to use text and mix with some hash to make sure the id is unique. not to translate Chinese. and I just do as you suggest

**Comment by valeriangalliat** [comment] 2016-05-23 15:23
Makes sense, well in this case your `slugify` function can just be `title => title`, there's already code that adds `-1`, `-2` at the end of the ID in case an ID was already used.

I might default to this in the next major version, simple and easy. 👍

**Comment by airwin** [comment] 2016-11-22 12:09
maybe a full solution:
```
var transliteration = require('transliteration')
var markdownItAnchorSlugCache = {}
// and use custom slugify function in markdown-it-anchor config
slugify: function(s) {
  var slug = transliteration.slugify(s, {lowercase: true, separator: '-', ignore: []})
  if (markdownItAnchorSlugCache[slug]) {
    slug += '-' + (markdownItAnchorSlugCache[slug]++)
  } else {
    markdownItAnchorSlugCache[slug] = 1
  }

  return slug
}
```

**Closed** 2018-06-14 14:13 UTC

**Comment by nagaozen** [comment] 2018-06-14 14:58
Fixed by version `5.0.0`.
